###############
## 
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'Deraining'
  SESSION: 'Rain800'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 4
  NUM_EPOCHS: 250
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 5
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 128
  TRAIN_DIR: '../Deraining/Datasets/train/Rain800'       # path to training data
  VAL_DIR: '../Deraining/Datasets/test/Rain800' # path to validation data
  SAVE_DIR: './checkpoints1/'           # path to save models and images
  # SAVE_IMAGES: False
